#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement

test ! -n "${1}" && printf "usage: ${0} <git-repo-url>\n" && exit 1
git_repo="$1"

folder_name="${git_repo##*/}"
folder_name="${folder_name%.git}"
folder_path="$HOME/prog/personal/sources/$folder_name"

wget -q "$git_repo" 
if test ! $? -eq 0; then
  printf "$git_repo does not exist"
  exit 2
else
  rm "$folder_name".git
  git clone --depth 1 "$git_repo" "$folder_path"

  cd "$folder_path"
  find . -type f -iname "*.[chS]" | xargs ctags --c-kinds=+lpx -R
  cd -
fi

