#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement

test ! -n "${1}" && printf "usage: ${0} <git-repo-url>\n" && exit 1
git_repo="$1"

folder_name="${git_repo##*/}"
folder_name="${folder_name%.git}"
folder_name="$HOME/prog/personal/sources/$folder_name"
git clone --depth 1 "$git_repo" "$folder_name"

cd "$folder_name"
find . -type f -iname "*.[chS]" | xargs ctags --c-kinds=+lpx -R
cd -
