#!/bin/bash
# SPDX-License-Identifier: zlib-acknowledgement

[ ! $# -ge 2 ] && printf "usage: ${0##*/} <project-abbrev> '<project-name>'\n" && exit 1

project_abbrev="${1}"
project_name="${2}"

copy_codefiles() {
  cp -r "$HOME/prog/personal/scripts/desktop-template" "${project_abbrev}"

  # TODO(Ryan): Run some name translation?

  mv "${project_abbrev}/code/desktop.cpp" "${project_abbrev}/code/${project_abbrev}.cpp" 
  mv "${project_abbrev}/code/desktop.h" "${project_abbrev}/code/${project_abbrev}.h" 

  mv "${project_abbrev}/.gitignore.copy" "${project_abbrev}/.gitignore"

  chmod +x "${project_abbrev}/misc/build"
}

create_license() {
cat <<EOF > "${project_abbrev}/LICENSE"
zlib License

(C) $(date +%Y) Ryan McClue 

This software is provided 'as-is', without any express or implied
warranty.  In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, anv acknowledgment in the product documentation would be
   appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.
EOF
}

create_readme() {
cat <<EOF > "${project_abbrev}/README.md"
<!-- SPDX-License-Identifier: zlib-acknowledgement -->

# ${project_abbrev^^} (${project_name})
> ![Github](https://img.shields.io/github/license/ryan-mcclue/${project_abbrev})
EOF
}

copy_codefiles
create_license
create_readme

dark_blue_fg='\e[01;34m'
colour_reset='\e[0m'
printf "${dark_blue_fg}======================================================\n"
printf "Update project specifics in misc/build, code/* and README!\n"
printf "Update debugger keyboard shortcut specifics in sim/simulate-input.c!\n"
printf "======================================================\n${colour_reset}"
