#!/bin/bash
# SPDX-License-Identifier: zlib-acknowledgement

test ! -n "${1}" -o ! -n "${2}" && printf "usage: ${0##*/} <project-abbrev> '<project-name>'\n" \
  && exit 1
project_abbrev="${1}"
project_name="${2}"

create_license() {
cat <<EOF > LICENSE
zlib License

(C) $(date +%Y) Ryan McClue 

This software is provided 'as-is', without any express or implied
warranty.  In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.
EOF
}

create_readme() {
cat <<EOF > README.md
<!-- SPDX-License-Identifier: zlib-acknowledgement -->

# ${project_abbrev^^} (${project_name})
> ![Github](https://img.shields.io/github/license/ryan-mcclue/${project_abbrev})
EOF
}

create_cmakefiles() {
mkdir -p cmake/toolchains

wget -O cmake/CPM.cmake \
  https://github.com/cpm-cmake/CPM.cmake/releases/latest/download/get_cpm.cmake

cp "$HOME/prog/personal/scripts/tbc/CMockaTesting.cmake" cmake/
cp "$HOME/prog/personal/scripts/tbc/arm-none-eabi-gcc.cmake" cmake/toolchains
cp "$HOME/prog/personal/scripts/tbc/arm-none-eabi-gcc-mcu.cmake" cmake/toolchains

bsp_driver_files='${BSP_DRIVER_FILES}'
bsp_compiler_flags='${BSP_COMPILER_FLAGS}'
cmake_source_dir='${CMAKE_SOURCE_DIR}'
cmake_objcopy='${CMAKE_OBJCOPY}'
compiler_flags='${COMPILER_FLAGS}'
cat <<EOF > CMakeLists.txt
# SPDX-License-Identifier: zlib-acknowledgement

cmake_minimum_required(VERSION 3.20)
project(${project_abbrev^^}
        VERSION 0.0.1
        DESCRIPTION "${project_name}"
        LANGUAGES C ASM)
set_property(GLOBAL PROPERTY C_STANDARD 11)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE 
    BOOL "Export compile commands" FORCE)

set(BSP_DRIVER_FILES
  BSP/tra/startup_stm32f429xx.s
  BSP/tra/Core/Src/system_stm32f4xx.c
)
set(BSP_COMPILER_FLAGS
  -DUSE_HAL_DRIVER
  -DSTM32F429xx
  -I${cmake_source_dir}/BSP/tra/Core/Inc
  -I${cmake_source_dir}/BSP/tra/Drivers/STM32F4xx_HAL_Driver/Inc
  -I${cmake_source_dir}/BSP/tra/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
  -I${cmake_source_dir}/BSP/tra/Drivers/CMSIS/Device/ST/STM32F4xx/Include
  -I${cmake_source_dir}/BSP/tra/Drivers/CMSIS/Include
) 

add_executable(${project_abbrev})
target_sources(${project_abbrev} PRIVATE
  ${bsp_driver_files}
  code/${project_abbrev}.c
)
set(COMPILER_FLAGS
  ${bsp_compiler_flags}
  -Icode
  
  -D${project_abbrev^^}_INTERNAL
  -D${project_abbrev^^}_SLOW
  
  -O0 -g -ggdb3
  
  -Werror -Wall -Wextra -pedantic -Warray-bounds=2
  
  -Wno-unused-variable -Wno-unused-function -Wno-unused-but-set-variable
  -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings
  -Wno-unused-result
  
  -fdata-sections -ffunction-sections
)
target_compile_options(${project_abbrev} PRIVATE
  ${compiler_flags}
)
target_link_options(tra PRIVATE
  -specs=nano.specs -lc -lm -lnosys
  -Wl,--gc-sections
)

add_custom_command(
  TARGET ${project_abbrev} POST_BUILD
  COMMAND ${cmake_objcopy} ARGS -O binary ${project_abbrev} ${project_abbrev}.bin
  COMMAND ${cmake_objcopy} ARGS -O ihex ${project_abbrev} ${project_abbrev}.hex
)

#include(cmake/CMockaTesting.cmake)
#cmocka_add_test(test-${project_abbrev}
#  "${bsp_driver_files};code/${project_abbrev}.c;tests/test-${project_abbrev}.c"
#)
EOF

}

create_codefiles() {
  mkdir -p code tests misc work build
  cp "$HOME/prog/personal/scripts/tbc/create" misc/
  cp "$HOME/prog/personal/scripts/tbc/build" misc/
  cp "$HOME/prog/personal/scripts/tbc/run-tests" misc/
  cp "$HOME/prog/personal/scripts/tbc/flash-runner" misc/
  cp "$HOME/prog/personal/scripts/tbc/.gdbinit" work/
cat <<EOF > code/${project_abbrev}.c
// SPDX-License-Identifier: zlib-acknowledgement

#if defined(TESTING)
  int testable_main(void)
#else
  int main(void)
#endif
{
  return 0;
}
EOF

cat <<EOF > tests/test-${project_abbrev}.c
// SPDX-License-Identifier: zlib-acknowledgement

#include <stdarg.h>
#include <stdint.h>
#include <stddef.h>
#include <setjmp.h>
#include <limits.h>
#include <cmocka.h>

extern int testable_main(void);

void
test_${project_abbrev}(void **state)
{
  assert_int_equal(testable_main(), 0);
}

int 
main(void)
{
	const struct CMUnitTest tests[] = {
    cmocka_unit_test(test_${project_abbrev}),
  };

  return cmocka_run_group_tests(tests, NULL, NULL);
}
EOF
cat <<EOF > misc/flash
device STM32F429ZI 
si 1
speed 4000
loadbin build/${project_abbrev}.bin 0x8000000
r
g
qc
EOF
cat <<EOF > misc/lint
#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

EOF
chmod +x misc/flash misc/lint
}

create_gitfiles() {
cat <<EOF > .gitignore
# SPDX-License-Identifier: zlib-acknowledgement

*

!.gitignore
!README.md
!LICENSE
!CMakeLists.txt

!cmake/
!cmake/toolchains
!cmake/**/*.cmake

!misc/
!misc/**/*

!code/
!code/**/*.[chs]
!code/**/*.ld

!tests/
!tests/**/*.[ch]

!work/
!work/.gdbinit
EOF
}

create_license
create_readme
create_cmakefiles
create_codefiles
create_gitfiles

dark_blue_fg='\e[01;34m'
colour_reset='\e[0m'
printf "${dark_blue_fg}======================================================\n"
printf "Update BSP driver and compiler flags in CMakeLists.txt!\n"
printf "Update MCU information in CMake MCU toolchain file!\n"
printf "Update MCU information in flash script!\n"
printf "======================================================\n${colour_reset}"
