#!/bin/bash

notify-send "TODO: automated crash reporting!" 
# TODO: https://lance.handmade.network/blog/p/8491-automated_crash_reporting_in_basically_one_400-line_function#26634

links=()
links+=(" https://techblog.paalijarvi.fi/ ")
links+=(" https://justine.lol/sizetricks/ ")
links+=(" https://coffeebeforearch.github.io/ ")
links+=(" https://hackaday.com/2015/11/24/building-the-infinite-matrix-of-tamagotchis/ ")
links+=(" https://jaycarlson.net/microcontrollers/ ")
links+=(" https://tratt.net/laurie/blog/archive.html ")
links+=(" https://lemire.me/blog/ ")
links+=(" https://travisdowns.github.io/ ")
links+=(" https://carstein.github.io/ ")
links+=(" https://wrongbaud.github.io/ ")
links+=(" https://m0agx.eu/pages/archives.html ")
links+=(" https://fabiensanglard.net/ ")
links+=(" https://www.gingerbill.org/article/ ")
links+=(" https://patternsinthemachine.net/ ")
links+=(" https://blog.feabhas.com/ ")
links+=(" https://dojofive.com/blog/ ")
links+=(" https://www.embeddedrelated.com/blogs.php ")
links+=(" https://embeddeduse.com/ ")

firefox ${links[*]}
