#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement

test ! -n "${2}" && printf "usage: git-search [commit|code] <search>\n" && exit 1

# NOTE(Ryan): What commit contained the search term
if test "${1}" = "commit"; then
  git log -S "${2}" 
# NOTE(Ryan): What code snippets contained the search term
elif test "${1}" = "code"; then
  git rev-list --all | xargs git grep "${2}" 
else
  printf "usage: ${0} [commit|code] <search>\n"
  exit 2
fi
