#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement

mkdir -p build

# NOTE(Ryan): -fsanitize=thread, -fsanitize=address 
ignored_warning_flags="-Wno-unused-variable -Wno-unused-function -Wno-unused-but-set-variable
  -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings
  -Wno-unused-result"

dev_type_flags="-O0 -g -ggdb3 -DHHF_SLOW -DHHF_INTERNAL"

# TODO(Ryan): Are we fine with breaking IEEE floating point (losing precision) for speed?
common_flags="$ignored_warnings -Icode -fno-exceptions -fno-rtti -std=c++2a -Werror -Wall -Wextra -pedantic 
  -Warray-bounds=2 -march=native -ffast-math -ffunction-sections -fdata-sections -Wl,--gc-sections"

libraries=""

g++ $common_compiler_flags $dev_type_flags \
  code/ubuntu-hhf.cpp -o build/ubuntu-hhf \
  $libraries

./build/ubuntu-hhf
