#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

for test_binary in $(find build/ -maxdepth 1 -type f -iname "test-*"); do
  export TEST_FILE_NAME="${test_binary}" 
  script --quiet --command misc/run-qemu >/dev/null
  # TODO(Ryan): Process output here to determine if error occurred and terminate
  grep '(qemu)' typescript
done

# IMPORTANT(Ryan): CTest configured to use work/ as working directory already
ctest -R 'test-.*' --test-dir build/

# IMPORTANT(Ryan): Useful to debug unsupported qemu-system, use qemu-user
# qemu-arm -g 1234 build/tra
# arm-none-eabi-gdb -q --nh -ex 'file build/tra' -ex 'target remote localhost:1234'
# qemu-system-gnuarmeclipse -machine STM32F429I-Discovery -g 1234 -nographic -kernel build/tra

 qemu-system-gnuarmeclipse --verbose --verbose --board STM32F4-Discovery \
 --mcu STM32F429ZI -d unimp,guest_errors \
 --nographic --image build/tra \
 -no-reboot \
 --semihosting-config enable=on,target=native \
 --semihosting-cmdline tra
