#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

# IMPORTANT(Ryan): Ensure working directory is work/
cd work/
for test_binary in $(find ../build/ -maxdepth 1 -type f -iname "test-*"); do
  qemu-arm ${test_binary}
  test $? -ne 0 && exit 1
done
cd -

# IMPORTANT(Ryan): CTest configured to use work/ as working directory already
ctest -R 'test-.*' --test-dir build/
